add ImageBlock component
zetkin/www.zetkin.org pull request #12
Opened 2022-02-23 14:21 UTC by ziggabyte

2022-02-24 14:15 UTC, Bagera requested changes
We should have more semantic elements than div and p here

2022-02-24 14:15 UTC, Bagera commented on frontend/src/components/ImageBlock.tsx
> +    <Box>
I think a figure with a figcaption is a better choice of elements here.

2022-02-24 17:03 UTC, ziggabyte commented on frontend/src/components/ImageBlock.tsx
> +    <Box>
Will exchange! Thank you!

2022-02-28 08:28 UTC, ziggabyte commented on frontend/src/components/ImageBlock.tsx
> +  const setImageSize = () => {
In the conversation with Robin and Richard it was requested that the editor could decide the size of the displayed image in a dropdown in the cms, and this is my interpretation of how to take the value the editor decided and adjust the size of image from that.

2022-02-28 13:42 UTC, Bagera commented on frontend/src/components/ImageBlock.tsx
> +  const setImageSize = () => {
I see. I just don't like the random values used. Is it supposed to crop the images? Else I think we should keep the the aspect ratio of the original images.

I think that if we could make better guesses on the sizes.

2022-02-28 13:52 UTC, ziggabyte commented on frontend/src/components/ImageBlock.tsx
> +  const setImageSize = () => {
So I put original image size in all until we have better values to put into it?

2022-02-28 14:24 UTC, Bagera commented on frontend/src/components/ImageBlock.tsx
> +  const setImageSize = () => {
Sure, that might be better for now.

2022-02-28 17:37 UTC, Bagera approved these changes

2022-02-28 18:11 UTC, merged